# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
staticResourcesRootUrl:       http://toolsrallyteam.no-static-resources.s3.amazonaws.com
designTemplateThemeRootUrl:   http://toolsrallyteam.no-static-resources.s3.amazonaws.com/design-templates/design-03/themes/theme-01
blogImagesRootUrl:            http://bieltvedtrallysport.no/resources/blog-images
imageGalleryRootUrl:          http://toolsrallyteam.no-static-resources.s3.amazonaws.com/images/image-gallery

firebaseGjestebokJsonUrl:     https://luminous-inferno-8888.firebaseio.com/gjestebok.json?print=pretty


collections:
  video:
    output: true
  fotoalbum:
    output: true

title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
